allowBuilds:
  '@prisma/engines': true
  argon2: true
  msgpackr-extract: true
  prisma: true
  unrs-resolver: true
onlyBuiltDependencies:
  - argon2
  - "@prisma/engines"
  - prisma
  - msgpackr-extract
  - unrs-resolver 